/*
 * OilUsage.API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using OilUsage.API.NetClient.Client;
using OilUsage.API.NetClient.Api;
// uncomment below to import models
//using OilUsage.API.NetClient.Model;

namespace OilUsage.API.NetClient.Test.Api
{
    /// <summary>
    ///  Class for testing OilsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class OilsApiTests : IDisposable
    {
        private OilsApi instance;

        public OilsApiTests()
        {
            instance = new OilsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OilsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' OilsApi
            //Assert.IsType<OilsApi>(instance);
        }

        /// <summary>
        /// Test ApiOilsGet
        /// </summary>
        [Fact]
        public void ApiOilsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ApiOilsGet();
            //Assert.IsType<List<OilDto>>(response);
        }

        /// <summary>
        /// Test ApiOilsIdDelete
        /// </summary>
        [Fact]
        public void ApiOilsIdDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int id = null;
            //instance.ApiOilsIdDelete(id);
        }

        /// <summary>
        /// Test ApiOilsIdGet
        /// </summary>
        [Fact]
        public void ApiOilsIdGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int id = null;
            //var response = instance.ApiOilsIdGet(id);
            //Assert.IsType<string>(response);
        }

        /// <summary>
        /// Test ApiOilsIdPut
        /// </summary>
        [Fact]
        public void ApiOilsIdPutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int id = null;
            //string body = null;
            //instance.ApiOilsIdPut(id, body);
        }

        /// <summary>
        /// Test ApiOilsPost
        /// </summary>
        [Fact]
        public void ApiOilsPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string body = null;
            //instance.ApiOilsPost(body);
        }
    }
}
