openapi: 3.0.1
info:
  title: OilUsage.API
  version: "1.0"
servers:
- url: /
security:
- ApiKey: []
paths:
  /api/Issues:
    get:
      responses:
        "200":
          content:
            text/plain:
              schema:
                items:
                  $ref: '#/components/schemas/IssueDto'
                type: array
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/IssueDto'
                type: array
            text/json:
              schema:
                items:
                  $ref: '#/components/schemas/IssueDto'
                type: array
          description: Success
      tags:
      - Issues
  /api/Issues/GetOilForInternalUsage:
    get:
      parameters:
      - explode: true
        in: query
        name: issues
        required: false
        schema:
          items:
            type: string
          type: array
        style: form
      responses:
        "200":
          content:
            text/plain:
              schema:
                items:
                  $ref: '#/components/schemas/OilUsageDto'
                type: array
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/OilUsageDto'
                type: array
            text/json:
              schema:
                items:
                  $ref: '#/components/schemas/OilUsageDto'
                type: array
          description: Success
      tags:
      - Issues
  /api/Issues/GetOilForCareProducts:
    get:
      parameters:
      - explode: true
        in: query
        name: issues
        required: false
        schema:
          items:
            type: string
          type: array
        style: form
      responses:
        "200":
          content:
            text/plain:
              schema:
                items:
                  $ref: '#/components/schemas/OilUsageDto'
                type: array
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/OilUsageDto'
                type: array
            text/json:
              schema:
                items:
                  $ref: '#/components/schemas/OilUsageDto'
                type: array
          description: Success
      tags:
      - Issues
  /api/Issues/GetOilForBaseCare:
    get:
      parameters:
      - explode: true
        in: query
        name: issues
        required: false
        schema:
          items:
            type: string
          type: array
        style: form
      responses:
        "200":
          content:
            text/plain:
              schema:
                items:
                  $ref: '#/components/schemas/OilUsageDto'
                type: array
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/OilUsageDto'
                type: array
            text/json:
              schema:
                items:
                  $ref: '#/components/schemas/OilUsageDto'
                type: array
          description: Success
      tags:
      - Issues
  /api/Oils:
    get:
      responses:
        "200":
          content:
            text/plain:
              schema:
                items:
                  $ref: '#/components/schemas/OilDto'
                type: array
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/OilDto'
                type: array
            text/json:
              schema:
                items:
                  $ref: '#/components/schemas/OilDto'
                type: array
          description: Success
      tags:
      - Oils
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: string
          text/json:
            schema:
              type: string
          application/*+json:
            schema:
              type: string
      responses:
        "200":
          description: Success
      tags:
      - Oils
  /api/Oils/{id}:
    delete:
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          format: int32
          type: integer
        style: simple
      responses:
        "200":
          description: Success
      tags:
      - Oils
    get:
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          format: int32
          type: integer
        style: simple
      responses:
        "200":
          content:
            text/plain:
              schema:
                type: string
            application/json:
              schema:
                type: string
            text/json:
              schema:
                type: string
          description: Success
      tags:
      - Oils
    put:
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          format: int32
          type: integer
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              type: string
          text/json:
            schema:
              type: string
          application/*+json:
            schema:
              type: string
      responses:
        "200":
          description: Success
      tags:
      - Oils
components:
  schemas:
    IssueDto:
      additionalProperties: false
      example:
        name: name
        issueGuid: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      properties:
        issueGuid:
          format: uuid
          type: string
        name:
          nullable: true
          type: string
      type: object
    OilDto:
      additionalProperties: false
      example:
        name: name
        oilGuid: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      properties:
        oilGuid:
          format: uuid
          type: string
        name:
          nullable: true
          type: string
      type: object
    OilUsageDto:
      additionalProperties: false
      example:
        usage: usage
        name: name
        issues:
        - issues
        - issues
        oilGuid: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      properties:
        oilGuid:
          format: uuid
          type: string
        usage:
          nullable: true
          type: string
        name:
          nullable: true
          type: string
        issues:
          items:
            type: string
          nullable: true
          type: array
      type: object
  securitySchemes:
    ApiKey:
      description: ApiKey must appear in header
      in: header
      name: X-API-Key
      type: apiKey

