/*
 * OilUsage.API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using OilUsage.API.NetClient.Client;
using OilUsage.API.NetClient.Model;

namespace OilUsage.API.NetClient.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IIssuesApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="OilUsage.API.NetClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>List&lt;IssueDto&gt;</returns>
        List<IssueDto> ApiIssuesGet(int operationIndex = 0);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="OilUsage.API.NetClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of List&lt;IssueDto&gt;</returns>
        ApiResponse<List<IssueDto>> ApiIssuesGetWithHttpInfo(int operationIndex = 0);
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="OilUsage.API.NetClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="issues"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>List&lt;OilUsageDto&gt;</returns>
        List<OilUsageDto> ApiIssuesGetOilForBaseCareGet(List<string> issues = default(List<string>), int operationIndex = 0);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="OilUsage.API.NetClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="issues"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of List&lt;OilUsageDto&gt;</returns>
        ApiResponse<List<OilUsageDto>> ApiIssuesGetOilForBaseCareGetWithHttpInfo(List<string> issues = default(List<string>), int operationIndex = 0);
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="OilUsage.API.NetClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="issues"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>List&lt;OilUsageDto&gt;</returns>
        List<OilUsageDto> ApiIssuesGetOilForCareProductsGet(List<string> issues = default(List<string>), int operationIndex = 0);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="OilUsage.API.NetClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="issues"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of List&lt;OilUsageDto&gt;</returns>
        ApiResponse<List<OilUsageDto>> ApiIssuesGetOilForCareProductsGetWithHttpInfo(List<string> issues = default(List<string>), int operationIndex = 0);
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="OilUsage.API.NetClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="issues"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>List&lt;OilUsageDto&gt;</returns>
        List<OilUsageDto> ApiIssuesGetOilForInternalUsageGet(List<string> issues = default(List<string>), int operationIndex = 0);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="OilUsage.API.NetClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="issues"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of List&lt;OilUsageDto&gt;</returns>
        ApiResponse<List<OilUsageDto>> ApiIssuesGetOilForInternalUsageGetWithHttpInfo(List<string> issues = default(List<string>), int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IIssuesApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="OilUsage.API.NetClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;IssueDto&gt;</returns>
        System.Threading.Tasks.Task<List<IssueDto>> ApiIssuesGetAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="OilUsage.API.NetClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;IssueDto&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<IssueDto>>> ApiIssuesGetWithHttpInfoAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="OilUsage.API.NetClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="issues"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;OilUsageDto&gt;</returns>
        System.Threading.Tasks.Task<List<OilUsageDto>> ApiIssuesGetOilForBaseCareGetAsync(List<string> issues = default(List<string>), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="OilUsage.API.NetClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="issues"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;OilUsageDto&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<OilUsageDto>>> ApiIssuesGetOilForBaseCareGetWithHttpInfoAsync(List<string> issues = default(List<string>), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="OilUsage.API.NetClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="issues"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;OilUsageDto&gt;</returns>
        System.Threading.Tasks.Task<List<OilUsageDto>> ApiIssuesGetOilForCareProductsGetAsync(List<string> issues = default(List<string>), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="OilUsage.API.NetClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="issues"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;OilUsageDto&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<OilUsageDto>>> ApiIssuesGetOilForCareProductsGetWithHttpInfoAsync(List<string> issues = default(List<string>), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="OilUsage.API.NetClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="issues"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;OilUsageDto&gt;</returns>
        System.Threading.Tasks.Task<List<OilUsageDto>> ApiIssuesGetOilForInternalUsageGetAsync(List<string> issues = default(List<string>), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="OilUsage.API.NetClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="issues"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;OilUsageDto&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<OilUsageDto>>> ApiIssuesGetOilForInternalUsageGetWithHttpInfoAsync(List<string> issues = default(List<string>), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IIssuesApi : IIssuesApiSync, IIssuesApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class IssuesApi : IIssuesApi
    {
        private OilUsage.API.NetClient.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="IssuesApi"/> class.
        /// </summary>
        /// <returns></returns>
        public IssuesApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="IssuesApi"/> class.
        /// </summary>
        /// <returns></returns>
        public IssuesApi(string basePath)
        {
            this.Configuration = OilUsage.API.NetClient.Client.Configuration.MergeConfigurations(
                OilUsage.API.NetClient.Client.GlobalConfiguration.Instance,
                new OilUsage.API.NetClient.Client.Configuration { BasePath = basePath }
            );
            this.Client = new OilUsage.API.NetClient.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new OilUsage.API.NetClient.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = OilUsage.API.NetClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="IssuesApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public IssuesApi(OilUsage.API.NetClient.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = OilUsage.API.NetClient.Client.Configuration.MergeConfigurations(
                OilUsage.API.NetClient.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new OilUsage.API.NetClient.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new OilUsage.API.NetClient.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = OilUsage.API.NetClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="IssuesApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public IssuesApi(OilUsage.API.NetClient.Client.ISynchronousClient client, OilUsage.API.NetClient.Client.IAsynchronousClient asyncClient, OilUsage.API.NetClient.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = OilUsage.API.NetClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public OilUsage.API.NetClient.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public OilUsage.API.NetClient.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public OilUsage.API.NetClient.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public OilUsage.API.NetClient.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="OilUsage.API.NetClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>List&lt;IssueDto&gt;</returns>
        public List<IssueDto> ApiIssuesGet(int operationIndex = 0)
        {
            OilUsage.API.NetClient.Client.ApiResponse<List<IssueDto>> localVarResponse = ApiIssuesGetWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="OilUsage.API.NetClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of List&lt;IssueDto&gt;</returns>
        public OilUsage.API.NetClient.Client.ApiResponse<List<IssueDto>> ApiIssuesGetWithHttpInfo(int operationIndex = 0)
        {
            OilUsage.API.NetClient.Client.RequestOptions localVarRequestOptions = new OilUsage.API.NetClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = OilUsage.API.NetClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = OilUsage.API.NetClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }


            localVarRequestOptions.Operation = "IssuesApi.ApiIssuesGet";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (ApiKey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<List<IssueDto>>("/api/Issues", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiIssuesGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="OilUsage.API.NetClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;IssueDto&gt;</returns>
        public async System.Threading.Tasks.Task<List<IssueDto>> ApiIssuesGetAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            OilUsage.API.NetClient.Client.ApiResponse<List<IssueDto>> localVarResponse = await ApiIssuesGetWithHttpInfoAsync(operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="OilUsage.API.NetClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;IssueDto&gt;)</returns>
        public async System.Threading.Tasks.Task<OilUsage.API.NetClient.Client.ApiResponse<List<IssueDto>>> ApiIssuesGetWithHttpInfoAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            OilUsage.API.NetClient.Client.RequestOptions localVarRequestOptions = new OilUsage.API.NetClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = OilUsage.API.NetClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = OilUsage.API.NetClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }


            localVarRequestOptions.Operation = "IssuesApi.ApiIssuesGet";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (ApiKey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<List<IssueDto>>("/api/Issues", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiIssuesGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="OilUsage.API.NetClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="issues"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>List&lt;OilUsageDto&gt;</returns>
        public List<OilUsageDto> ApiIssuesGetOilForBaseCareGet(List<string> issues = default(List<string>), int operationIndex = 0)
        {
            OilUsage.API.NetClient.Client.ApiResponse<List<OilUsageDto>> localVarResponse = ApiIssuesGetOilForBaseCareGetWithHttpInfo(issues);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="OilUsage.API.NetClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="issues"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of List&lt;OilUsageDto&gt;</returns>
        public OilUsage.API.NetClient.Client.ApiResponse<List<OilUsageDto>> ApiIssuesGetOilForBaseCareGetWithHttpInfo(List<string> issues = default(List<string>), int operationIndex = 0)
        {
            OilUsage.API.NetClient.Client.RequestOptions localVarRequestOptions = new OilUsage.API.NetClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = OilUsage.API.NetClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = OilUsage.API.NetClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            if (issues != null)
            {
                localVarRequestOptions.QueryParameters.Add(OilUsage.API.NetClient.Client.ClientUtils.ParameterToMultiMap("multi", "issues", issues));
            }

            localVarRequestOptions.Operation = "IssuesApi.ApiIssuesGetOilForBaseCareGet";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (ApiKey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<List<OilUsageDto>>("/api/Issues/GetOilForBaseCare", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiIssuesGetOilForBaseCareGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="OilUsage.API.NetClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="issues"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;OilUsageDto&gt;</returns>
        public async System.Threading.Tasks.Task<List<OilUsageDto>> ApiIssuesGetOilForBaseCareGetAsync(List<string> issues = default(List<string>), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            OilUsage.API.NetClient.Client.ApiResponse<List<OilUsageDto>> localVarResponse = await ApiIssuesGetOilForBaseCareGetWithHttpInfoAsync(issues, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="OilUsage.API.NetClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="issues"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;OilUsageDto&gt;)</returns>
        public async System.Threading.Tasks.Task<OilUsage.API.NetClient.Client.ApiResponse<List<OilUsageDto>>> ApiIssuesGetOilForBaseCareGetWithHttpInfoAsync(List<string> issues = default(List<string>), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            OilUsage.API.NetClient.Client.RequestOptions localVarRequestOptions = new OilUsage.API.NetClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = OilUsage.API.NetClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = OilUsage.API.NetClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            if (issues != null)
            {
                localVarRequestOptions.QueryParameters.Add(OilUsage.API.NetClient.Client.ClientUtils.ParameterToMultiMap("multi", "issues", issues));
            }

            localVarRequestOptions.Operation = "IssuesApi.ApiIssuesGetOilForBaseCareGet";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (ApiKey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<List<OilUsageDto>>("/api/Issues/GetOilForBaseCare", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiIssuesGetOilForBaseCareGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="OilUsage.API.NetClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="issues"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>List&lt;OilUsageDto&gt;</returns>
        public List<OilUsageDto> ApiIssuesGetOilForCareProductsGet(List<string> issues = default(List<string>), int operationIndex = 0)
        {
            OilUsage.API.NetClient.Client.ApiResponse<List<OilUsageDto>> localVarResponse = ApiIssuesGetOilForCareProductsGetWithHttpInfo(issues);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="OilUsage.API.NetClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="issues"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of List&lt;OilUsageDto&gt;</returns>
        public OilUsage.API.NetClient.Client.ApiResponse<List<OilUsageDto>> ApiIssuesGetOilForCareProductsGetWithHttpInfo(List<string> issues = default(List<string>), int operationIndex = 0)
        {
            OilUsage.API.NetClient.Client.RequestOptions localVarRequestOptions = new OilUsage.API.NetClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = OilUsage.API.NetClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = OilUsage.API.NetClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            if (issues != null)
            {
                localVarRequestOptions.QueryParameters.Add(OilUsage.API.NetClient.Client.ClientUtils.ParameterToMultiMap("multi", "issues", issues));
            }

            localVarRequestOptions.Operation = "IssuesApi.ApiIssuesGetOilForCareProductsGet";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (ApiKey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<List<OilUsageDto>>("/api/Issues/GetOilForCareProducts", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiIssuesGetOilForCareProductsGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="OilUsage.API.NetClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="issues"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;OilUsageDto&gt;</returns>
        public async System.Threading.Tasks.Task<List<OilUsageDto>> ApiIssuesGetOilForCareProductsGetAsync(List<string> issues = default(List<string>), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            OilUsage.API.NetClient.Client.ApiResponse<List<OilUsageDto>> localVarResponse = await ApiIssuesGetOilForCareProductsGetWithHttpInfoAsync(issues, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="OilUsage.API.NetClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="issues"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;OilUsageDto&gt;)</returns>
        public async System.Threading.Tasks.Task<OilUsage.API.NetClient.Client.ApiResponse<List<OilUsageDto>>> ApiIssuesGetOilForCareProductsGetWithHttpInfoAsync(List<string> issues = default(List<string>), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            OilUsage.API.NetClient.Client.RequestOptions localVarRequestOptions = new OilUsage.API.NetClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = OilUsage.API.NetClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = OilUsage.API.NetClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            if (issues != null)
            {
                localVarRequestOptions.QueryParameters.Add(OilUsage.API.NetClient.Client.ClientUtils.ParameterToMultiMap("multi", "issues", issues));
            }

            localVarRequestOptions.Operation = "IssuesApi.ApiIssuesGetOilForCareProductsGet";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (ApiKey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<List<OilUsageDto>>("/api/Issues/GetOilForCareProducts", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiIssuesGetOilForCareProductsGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="OilUsage.API.NetClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="issues"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>List&lt;OilUsageDto&gt;</returns>
        public List<OilUsageDto> ApiIssuesGetOilForInternalUsageGet(List<string> issues = default(List<string>), int operationIndex = 0)
        {
            OilUsage.API.NetClient.Client.ApiResponse<List<OilUsageDto>> localVarResponse = ApiIssuesGetOilForInternalUsageGetWithHttpInfo(issues);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="OilUsage.API.NetClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="issues"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of List&lt;OilUsageDto&gt;</returns>
        public OilUsage.API.NetClient.Client.ApiResponse<List<OilUsageDto>> ApiIssuesGetOilForInternalUsageGetWithHttpInfo(List<string> issues = default(List<string>), int operationIndex = 0)
        {
            OilUsage.API.NetClient.Client.RequestOptions localVarRequestOptions = new OilUsage.API.NetClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = OilUsage.API.NetClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = OilUsage.API.NetClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            if (issues != null)
            {
                localVarRequestOptions.QueryParameters.Add(OilUsage.API.NetClient.Client.ClientUtils.ParameterToMultiMap("multi", "issues", issues));
            }

            localVarRequestOptions.Operation = "IssuesApi.ApiIssuesGetOilForInternalUsageGet";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (ApiKey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<List<OilUsageDto>>("/api/Issues/GetOilForInternalUsage", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiIssuesGetOilForInternalUsageGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="OilUsage.API.NetClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="issues"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;OilUsageDto&gt;</returns>
        public async System.Threading.Tasks.Task<List<OilUsageDto>> ApiIssuesGetOilForInternalUsageGetAsync(List<string> issues = default(List<string>), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            OilUsage.API.NetClient.Client.ApiResponse<List<OilUsageDto>> localVarResponse = await ApiIssuesGetOilForInternalUsageGetWithHttpInfoAsync(issues, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="OilUsage.API.NetClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="issues"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;OilUsageDto&gt;)</returns>
        public async System.Threading.Tasks.Task<OilUsage.API.NetClient.Client.ApiResponse<List<OilUsageDto>>> ApiIssuesGetOilForInternalUsageGetWithHttpInfoAsync(List<string> issues = default(List<string>), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            OilUsage.API.NetClient.Client.RequestOptions localVarRequestOptions = new OilUsage.API.NetClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = OilUsage.API.NetClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = OilUsage.API.NetClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            if (issues != null)
            {
                localVarRequestOptions.QueryParameters.Add(OilUsage.API.NetClient.Client.ClientUtils.ParameterToMultiMap("multi", "issues", issues));
            }

            localVarRequestOptions.Operation = "IssuesApi.ApiIssuesGetOilForInternalUsageGet";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (ApiKey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-API-Key")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-API-Key", this.Configuration.GetApiKeyWithPrefix("X-API-Key"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<List<OilUsageDto>>("/api/Issues/GetOilForInternalUsage", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiIssuesGetOilForInternalUsageGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
