/*
 * OilUsage.API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using OilUsage.API.NetClient.Model;
using OilUsage.API.NetClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace OilUsage.API.NetClient.Test.Model
{
    /// <summary>
    ///  Class for testing IssueDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IssueDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IssueDto
        //private IssueDto instance;

        public IssueDtoTests()
        {
            // TODO uncomment below to create an instance of IssueDto
            //instance = new IssueDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IssueDto
        /// </summary>
        [Fact]
        public void IssueDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" IssueDto
            //Assert.IsType<IssueDto>(instance);
        }


        /// <summary>
        /// Test the property 'IssueGuid'
        /// </summary>
        [Fact]
        public void IssueGuidTest()
        {
            // TODO unit test for the property 'IssueGuid'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

    }

}
