/*
 * OilUsage.API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using OilUsage.API.NetClient.Model;
using OilUsage.API.NetClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace OilUsage.API.NetClient.Test.Model
{
    /// <summary>
    ///  Class for testing OilDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OilDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OilDto
        //private OilDto instance;

        public OilDtoTests()
        {
            // TODO uncomment below to create an instance of OilDto
            //instance = new OilDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OilDto
        /// </summary>
        [Fact]
        public void OilDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" OilDto
            //Assert.IsType<OilDto>(instance);
        }


        /// <summary>
        /// Test the property 'OilGuid'
        /// </summary>
        [Fact]
        public void OilGuidTest()
        {
            // TODO unit test for the property 'OilGuid'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

    }

}
