/*
 * OilUsage.API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using OilUsage.API.NetClient.Model;
using OilUsage.API.NetClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace OilUsage.API.NetClient.Test.Model
{
    /// <summary>
    ///  Class for testing OilUsageDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OilUsageDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OilUsageDto
        //private OilUsageDto instance;

        public OilUsageDtoTests()
        {
            // TODO uncomment below to create an instance of OilUsageDto
            //instance = new OilUsageDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OilUsageDto
        /// </summary>
        [Fact]
        public void OilUsageDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" OilUsageDto
            //Assert.IsType<OilUsageDto>(instance);
        }


        /// <summary>
        /// Test the property 'OilGuid'
        /// </summary>
        [Fact]
        public void OilGuidTest()
        {
            // TODO unit test for the property 'OilGuid'
        }
        /// <summary>
        /// Test the property 'Usage'
        /// </summary>
        [Fact]
        public void UsageTest()
        {
            // TODO unit test for the property 'Usage'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Issues'
        /// </summary>
        [Fact]
        public void IssuesTest()
        {
            // TODO unit test for the property 'Issues'
        }

    }

}
